spring:
    profiles:
        active:
        - dev
---
server:
    port: 10001
spring:
    profiles: eureka01
    application:
        name: eureka-server
eureka:
  client:
    service-url:
      # 设置服务注册中心地址，指向另一个注册中心
      defaultZone: http://eureka02:10002/eureka/
      # 设置eureka示例名称，预配置文件的变量为主
  instance:
    hostname: eureka01
---
server:
    port: 10002
spring:
    profiles: eureka02
    application:
        name: eureka-server
eureka:
  client:
    service-url:
      # 设置服务注册中心地址，指向另一个注册中心
      defaultZone: http://eureka01:10001/eureka/
      # 设置eureka示例名称，预配置文件的变量为主
  instance:
    hostname: eureka02